#!/bin/bash
# Generated recovery scripts run only through the fake, from both directory locations.
set -u
if [[ "${1:-}" != --bounded ]]; then
    for timer in /opt/homebrew/bin/timeout /opt/homebrew/bin/gtimeout; do
        if [[ -x "$timer" ]]; then exec "$timer" -k 2 240 "$BASH" "$0" --bounded "$@"; fi
    done
    "$BASH" "$0" --bounded "$@" & child=$!
    ( sleep 240; kill -TERM "$child" 2>/dev/null ) & watchdog=$!
    wait "$child"; status=$?
    kill "$watchdog" 2>/dev/null || true
    wait "$watchdog" 2>/dev/null || true
    exit "$status"
fi
shift
ROOT="${CHARACTERIZE_ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"
OBS="${CHAR_OBSERVATIONS:-$ROOT/tests/contracts/observations}"
SANDBOX=$(mktemp -d /tmp/nl5-recovery-characterize.XXXXXX) || exit 2
PASS=0 FAIL=0
finish() {
    local rc=$?
    printf 'SUMMARY recovery passed=%s failed=%s exit=%s\n' "$PASS" "$FAIL" "$rc"
    printf 'sandbox: %s\n' "$SANDBOX"
}
trap finish EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
ok() { printf 'ok: %s\n' "$1"; PASS=$((PASS + 1)); }
bad() { printf 'FAIL: %s\n' "$1"; FAIL=$((FAIL + 1)); }
check() { local label="$1"; shift; if "$@"; then ok "$label"; else bad "$label"; fi; }
BASH_REAL=$(/usr/bin/python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$BASH") || exit 2
for directory in "${BASH_REAL%/*}" /usr/bin /bin /usr/sbin /sbin; do
    [[ ! -e "$directory/adb" ]] || { bad "unexpected adb in $directory"; exit 2; }
done
PATH="$ROOT/tests/fake-adb:${BASH_REAL%/*}:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH
hash -r
mkdir -p "$OBS/recovery-traces" "$OBS/recovery-output" || exit 2
for knob in $(compgen -A variable FAKE_ADB_); do unset "$knob"; done
export FAKE_ADB_SU_MODE=direct FAKE_ADB_PROPAGATE_RC=1
new_state() {
    [[ "$(command -v adb)" == "$ROOT/tests/fake-adb/adb" ]] || { bad 'adb routing'; exit 2; }
    FAKE_ADB_STATE=$(mktemp -d "$SANDBOX/$1.XXXXXX") || exit 2
    export FAKE_ADB_STATE
    "$BASH" "$ROOT/tests/device-emu/seed.sh" "$FAKE_ADB_STATE" > /dev/null || exit 2
}
new_state control
printf '0123456789abcdef\n' > "$FAKE_ADB_STATE/control-seed"
check 'fake control decodes seeded token' test "$(adb __pt_control)" = 'pt-control:fedcba9876543210'
check 'control invocation recorded' grep -Fq '__pt_control' "$FAKE_ADB_STATE/invocations.log"
"$BASH" "$ROOT/tests/fixtures/block-fixture.sh" "$SANDBOX/fixture" > "$SANDBOX/fixture-paths" || exit 2
new_state generate
cp "$SANDBOX/fixture/full-system-backup.img" "$FAKE_ADB_STATE/blockdev" || exit 2
export BACKUP_DIR="$SANDBOX/generated" STREAM_CHUNK_MB=1 STREAM_STALL_SECS=3 STREAM_RETRIES=1
"$BASH_REAL" "$ROOT/scripts/MAKE_BACKUP.sh" > "$SANDBOX/generate.log" 2>&1
RC=$?
check 'real MAKE_BACKUP generates recovery artifact' test "$RC" = 0
[[ -f "$BACKUP_DIR/RESTORE.sh" && -f "$BACKUP_DIR/reset-launcher.sh" ]] || exit 2
cp -R "$BACKUP_DIR" "$SANDBOX/pristine" || exit 2
check 'generated RESTORE syntax' /bin/bash -n "$BACKUP_DIR/RESTORE.sh"
check 'generated reset syntax' /bin/bash -n "$BACKUP_DIR/reset-launcher.sh"
/usr/bin/python3 - "$BACKUP_DIR" "$OBS/recovery-menu.txt" <<'PY'
import json, os, re, sys
source = open(os.path.join(sys.argv[1], 'RESTORE.sh')).read()
with open(sys.argv[2], 'w') as out:
    out.write('Generated by a complete MAKE_BACKUP.sh run, not extracted functions.\n')
    out.write('Menu strings, in order (JSON quotes retain spaces):\n')
    for line in source.splitlines():
        if line.startswith('echo "Options:') or re.match(r'echo "  [1-4q]\. ', line):
            out.write(json.dumps(line[6:-1]) + '\n')
    out.write('Prompt strings (source; read -p is silent on piped stdin):\n')
    for prompt in re.findall(r'read -p "([^"]*)"', source):
        out.write(json.dumps(prompt) + '\n')
    out.write('reset-launcher.sh has no menu or prompt.\n')
PY
want_call() {
    local argument
    printf adb
    for argument in "$@"; do printf '\t%q' "$argument"; done
    printf '\n'
}
expected_trace() {
    case "$option/$path" in
        1/success) want_call shell cmd package set-home-activity com.newlink.hisilauncher/.WizardAciticity ;;
        1/failure) want_call shell cmd package set-home-activity 'Unknown command: get-home-activity' ;;
        2/success) want_call restore complete-app-backup.ab ;;
        3/success|3/failure)
            want_call push system.img /sdcard/
            want_call shell "su -c 'dd if=/sdcard/system.img of=/dev/block/mmcblk0p20 bs=1048576'"
            want_call shell rm -f /sdcard/system.img
            ;;
        4/success|4/masked-push)
            want_call push full-system-backup.img /sdcard/
            want_call reboot
            ;;
        reset/success|reset/failure)
            want_call shell cmd package set-home-activity com.newlink.hisilauncher
            want_call shell am start -a android.intent.action.MAIN -c android.intent.category.HOME
            ;;
    esac
}
for option in 1 2 3 4 q reset; do
    for path in success failure; do
        for location in in-place relocated; do
            new_state "$option-$path-$location"
            export FAKE_ADB_SU_MODE=direct FAKE_ADB_NO_DEVICE=0
            cp "$SANDBOX/fixture/full-system-backup.img" "$FAKE_ADB_STATE/blockdev" || exit 2
            mkdir -p "$FAKE_ADB_STATE/dev/block"
            # Restore the generated directory before preparing each independent input.
            cp -R "$SANDBOX/pristine/." "$BACKUP_DIR/" || exit 2
            case "$option/$path" in
                1/success) printf 'com.newlink.hisilauncher/.WizardAciticity\n' > "$BACKUP_DIR/current-home-activity.txt" ;;
                2/failure) rm "$BACKUP_DIR/complete-app-backup.ab" ;;
                3/success|3/failure)
                    head -c 4096 "$SANDBOX/fixture/full-system-backup.img" > "$BACKUP_DIR/system.img"
                    rm "$BACKUP_DIR/backup-manifest.txt"
                    [[ "$path" != failure ]] || export FAKE_ADB_SU_MODE=none
                    ;;
                4/failure) rm "$BACKUP_DIR/full-system-backup.img" ;;
                reset/failure) printf 'com.newlink.hisilauncher\n' > "$FAKE_ADB_STATE/packages_disabled" ;;
                q/failure) export FAKE_ADB_NO_DEVICE=1 ;;
            esac
            run_dir="$BACKUP_DIR"
            if [[ "$location" == relocated ]]; then
                run_dir=$(mktemp -d "$SANDBOX/relocated.XXXXXX") || exit 2
                cp -R "$BACKUP_DIR/." "$run_dir/" || exit 2
            fi
            script=RESTORE.sh
            [[ "$option" != reset ]] || script=reset-launcher.sh
            printf '%s\nRESTORE\n' "$option" > "$SANDBOX/input"
            ( cd "$run_dir" && "$BASH_REAL" "./$script" < "$SANDBOX/input" ) > "$SANDBOX/output.raw" 2>&1
            RC=$?
            /usr/bin/python3 - "$SANDBOX/output.raw" "$SANDBOX/output" "$SANDBOX" <<'PY'
import re, sys
text = re.sub(r'\x1b\[[0-9;]*m', '', open(sys.argv[1]).read()).replace(sys.argv[3], '<SANDBOX>')
open(sys.argv[2], 'w').write(text)
PY
            expected_trace > "$SANDBOX/expected-trace"
            if [[ -f "$FAKE_ADB_STATE/invocations.log" ]]; then
                cp "$FAKE_ADB_STATE/invocations.log" "$SANDBOX/trace"
            else
                : > "$SANDBOX/trace"
            fi
            check "$option $path $location exact command trace" cmp -s "$SANDBOX/expected-trace" "$SANDBOX/trace"
            expected_rc=0
            [[ "$option/$path" != 4/failure ]] || expected_rc=1
            check "$option $path $location exit $expected_rc" test "$RC" = "$expected_rc"
            case "$option/$path" in
                1/success)
                    check "$option $path $location accepted launcher" grep -Fxq 'Success' "$SANDBOX/output"
                    ;;
                1/failure)
                    check "$option $path $location saved diagnostic reaches fake" grep -Fxq 'Error: component get-home-activity not found' "$SANDBOX/output"
                    check "$option $path $location still claims success" grep -Fxq 'Launcher reset' "$SANDBOX/output"
                    ;;
                2/success)
                    check "$option $path $location fake restore unsupported" grep -Fxq 'fake-adb: unhandled subcommand: restore' "$SANDBOX/output"
                    ;;
                2/failure) check "$option $path $location missing app backup" grep -Fxq 'No app backup found' "$SANDBOX/output" ;;
                3/success)
                    check "$option $path $location unguarded partition bytes written in fake" cmp -s "$run_dir/system.img" "$FAKE_ADB_STATE/dev/block/mmcblk0p20"
                    ;;
                3/failure)
                    check "$option $path $location rejected su" grep -Fxq 'su: invalid option -- c' "$SANDBOX/output"
                    check "$option $path $location still claims restored" grep -Fxq 'System partition restored' "$SANDBOX/output"
                    ;;
                4/success)
                    check "$option $path $location fake reboot recorded" grep -Fxq '1' "$FAKE_ADB_STATE/reboots"
                    ;;
                4/failure) check "$option $path $location missing whole image" grep -Fxq 'No full-system-backup.img here' "$SANDBOX/output" ;;
                reset/failure)
                    check "$option $path $location disabled launcher refused" grep -Fxq 'Error: package com.newlink.hisilauncher is disabled' "$SANDBOX/output"
                    check "$option $path $location still claims default" grep -Fxq 'Launcher reset to default' "$SANDBOX/output"
                    ;;
            esac
            if [[ "$location" == in-place ]]; then
                cp "$SANDBOX/trace" "$OBS/recovery-traces/$option-$path.log"
                { printf 'exit=%s\n' "$RC"; cat "$SANDBOX/output"; } > "$OBS/recovery-output/$option-$path.txt"
            else
                check "$option $path relocated trace equals in-place" cmp -s "$OBS/recovery-traces/$option-$path.log" "$SANDBOX/trace"
                cp "$SANDBOX/trace" "$OBS/recovery-traces/$option-$path-relocated.log"
            fi
        done
    done
done

# The fake masks cp errors in push; measure that limit rather than inventing a fault knob.
new_state masked-push
export FAKE_ADB_SU_MODE=direct FAKE_ADB_NO_DEVICE=0
cp -R "$SANDBOX/pristine/." "$BACKUP_DIR/" || exit 2
mv "$FAKE_ADB_STATE/sdcard" "$FAKE_ADB_STATE/sdcard.saved"
printf 'not a directory\n' > "$FAKE_ADB_STATE/sdcard"
printf '4\nRESTORE\n' > "$SANDBOX/input"
( cd "$BACKUP_DIR" && "$BASH_REAL" ./RESTORE.sh < "$SANDBOX/input" ) > "$SANDBOX/masked-push.out" 2>&1
RC=$?
option=4 path=masked-push
expected_trace > "$SANDBOX/expected-trace"
check 'copy failure masked by fake push exit zero' test "$RC" = 0
check 'masked copy still reaches reboot, not streaming branch' cmp -s "$SANDBOX/expected-trace" "$FAKE_ADB_STATE/invocations.log"
check 'copy failure has a real error diagnostic' grep -Fq 'Not a directory' "$SANDBOX/masked-push.out"
cp "$FAKE_ADB_STATE/invocations.log" "$OBS/recovery-traces/4-masked-push.log"

/usr/bin/python3 - "$SANDBOX/pristine/RESTORE.sh" "$OBS/recovery-hazards.md" <<'PY'
import sys
source = open(sys.argv[1]).read().splitlines()
def line(fragment):
    hits = [str(i) for i, text in enumerate(source, 1) if fragment in text]
    return ', '.join(hits)
with open(sys.argv[2], 'w') as out:
    out.write('## Recovery baseline hazards\n\n')
    out.write('These traces describe fake execution, not proof of a working hardware restore. ')
    out.write('The generated directory was run as the current directory, then copied to a fresh path and run from there. ')
    out.write('Absolute invocation from an unrelated current directory is not tested.\n\n')
    out.write('- Successful full-image push is followed by reboot without a restore write. ')
    out.write('Observed in recovery-traces/4-success.log and its relocated twin; RESTORE.sh lines ' + line('adb push full-system') + ' and ' + line('adb reboot') + '.\n')
    out.write('- A failed push would enter a stdin whole-device dd according to RESTORE.sh line ' + line('cat full-system-backup.img | adb') + '. ')
    out.write('That branch is NOT EXECUTED: fake push always exits zero, even after a copy error. ')
    out.write('recovery-traces/4-masked-push.log records the measured masked-copy case, which still reboots. ')
    out.write('The missing-image failure is recovery-traces/4-failure.log (empty after the guard), RESTORE.sh line ' + line('if [[ ! -f full-system') + '.\n')
    out.write('- Partition option 3 accepts a 4096-byte image without any manifest or typed confirmation and issues dd. ')
    out.write('Observed byte-identical fake partition output and recovery-traces/3-success.log; RESTORE.sh lines ' + line('if [[ -f system.img') + ' and ' + line('dd if=/sdcard/system.img') + '. ')
    out.write('Its failed su case still prints System partition restored (recovery-traces/3-failure.log, recovery-output/3-failure.txt).\n')
    out.write('- Saved launcher text is forwarded unvalidated, including the generated Unknown command: get-home-activity diagnostic. ')
    out.write('Observed in recovery-traces/1-failure.log and recovery-output/1-failure.txt; RESTORE.sh lines ' + line('HOME=$(cat') + ' and ' + line('"${HOME:-') + '. ')
    out.write('The fake rejects it, yet the script prints Launcher reset and exits zero.\n')
    out.write('- Option 2 success names the file-present branch, NOT a successful restore. ')
    out.write('The fake does not implement adb restore; recovery-traces/2-success.log records the attempt and recovery-output/2-success.txt records its error. ')
    out.write('The missing-file branch makes no device call (2-failure.log).\n')
    out.write('- Quit has no failing action: q-failure.log uses a disconnected fake and remains empty, with exit zero. ')
    out.write('reset failure uses a disabled launcher; both reset commands still run and the script reports success.\n')
PY
[[ "$FAIL" == 0 ]]
